### ISSUE TITLE
Add asyncio async/await syntax

### ISSUE THREAD

**Issue by trevormccasland** [trevormccasland/dotalytics-api#6]
We should be able to use asyncio and leverage async/await syntax throughout the code base. The uvicorn documentation[1] shows an example of how to serve with asyncio.
[1] https://www.uvicorn.org/#running-programmatically

**Comment by iam-vipin** [comment]
Hello sir i know how to use Async and await in javascript i will try to implement in python give me a chance

**Comment by trevormccasland** [comment]
Hi @itsvipindev thanks for your interest! I'll assign this to you now. Let me know if you have any questions with getting started. You will need to get an API key using your steam account to use the API.

**Comment by iam-vipin** [comment]
Ok @trevormccasland  i will try my best thanks for assigning me this task

**Comment by trevormccasland** [comment]
Good luck! Just as an FYI, the `requests` library this project uses doesn't support async/await so that will need to swapped out with `httpx` or `aiohttp`
